name: 'Terraform flow'

description: 'Perform terraform flow in given directory'

inputs:
  directory:
    description: 'the directory where terraform should run'
    required: true
  var-file:
    description: 'the terraform variables that should be used. Relativ to the specified directory.'
    required: false
    default: ""
  backend-config:
    description: 'the backend configuration that should be usesd. Relativ to the specified directory.'
    required: true
    default: ""
  

runs:
  using: "composite"
  steps: 
    - name: Set parameters
      id: parameters
      shell: bash
      run: |
        USE_VAR_FILE=""
        if [ -n "${{ inputs.var-file }}" ]; then
          USE_VAR_FILE="-var-file "${{ inputs.var-file }}""
        fi
        echo "::set-output name=varFile::$USE_VAR_FILE"

        USE_BACKEND_CONFIG=""
        if [ -n "${{ inputs.backend-config }}" ]; then
          USE_BACKEND_CONFIG="-reconfigure -backend-config ${{ inputs.backend-config }}"
        fi
        echo "::set-output name=backendConfig::$USE_BACKEND_CONFIG"

    - name: Terraform Init
      id: init
      shell: bash
      run: |
        terraform init ${{ steps.parameters.outputs.varFile }} ${{ steps.parameters.outputs.backendConfig }} $upgrade
      working-directory: "${{ inputs.directory }}"

    - name: Terraform Validate
      id: validate
      shell: bash
      run: terraform validate -no-color
      working-directory: "${{ inputs.directory }}"

    - name: Terraform Plan
      id: plan
      shell: bash    
      run: terraform plan -no-color ${{ steps.parameters.outputs.varFile }}
      working-directory: "${{ inputs.directory }}"
  
    - name: Failed plan
      if: ${{ failure() }}
      env:
        PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
      id: failed-plan
      shell: bash
      run: |
        # const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
        const output = `#### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
        #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
        #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
        <details><summary>Show Plan</summary>
        \`\`\`\
        ${process.env.PLAN}
        \`\`\`
        </details>        

    - name: Terraform Apply
      id: apply
      shell: bash    
      run: terraform apply -auto-approve ${{ steps.parameters.outputs.varFile }}
      working-directory: "${{ inputs.directory }}"

