name: "Test"

env:
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

concurrency: azure_subscription_flow

on:
  push:

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Copy action.yml
        run: |
          mkdir -p .github/actions/terraform-flow
          cp action.yml .github/actions/terraform-flow/

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Test - empty var-file and empty backend-config
        uses: ./.github/actions/terraform-flow
        with:
          directory: "./test-1"
          var-file: ""
          backend-config: ""

      - name: Test - var-file and empty backend-config
        uses: ./.github/actions/terraform-flow
        with:
          directory: "./test-2"
          var-file: "../environment/variables.tfvars"
          backend-config: ""

      - name: Test - empty var-file and  backend-config
        uses: ./.github/actions/terraform-flow
        with:
          directory: "./test-3"
          var-file: ""
          backend-config: "../environment/backend.tf"

      - name: Verify backend-config
        run: |
          typeset -i count=$(ls -1 terraform.tfstate | wc -l)
          if [ "$count" -ne "1" ]; then
            exit 1
          fi
