name: "Azure Subscription Flow"

env:
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

concurrency: azure_subscription_flow

on:
  push:

jobs:
  test:
    name: "Test "
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Copy action.yml
        run: |
          mkdir -p .github/actions
          cp action.yml .github/actions/

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform - Test 1
        uses: ./.github/actions/action.yml
        with:
          directory: "./test-1"
          var-file: ""
          backend-config: ""

      - name: Terraform - Test 2
        uses: ./.github/actions/action.yml
        with:
          directory: "./test-2"
          var-file: "../environment/variables.tfvars"
          backend-config: ""
